name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: ./gradle wrapper

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExclusiveGame-APK
          path: app/build/outputs/apk/debug/app-debug.apk
